# Generated by Django 3.2.25 on 2024-09-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parrenttransaction',
            name='check_child_transacation_id_must_null',
        ),
        migrations.AddConstraint(
            model_name='parrenttransaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 5), ('child_transaction_id__isnull', True)), models.Q(('type', 6), ('child_transaction_id__isnull', True)), models.Q(models.Q(('type', 5), ('type', 6), _connector='OR'), _negated=True), _connector='OR'), name='check_child_transaction_id_must_null'),
        ),
    ]
