# Generated by Django 3.2.25 on 2024-09-23 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240923_0750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
