# Generated by Django 3.2.25 on 2024-09-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='special_recipient',
            field=models.BooleanField(default=False, help_text='Saat customer lain mengirim maka si pengirim tidak akan berlaku limit', verbose_name='Penerima spesial'),
        ),
    ]
